### ISSUE TITLE
upload for c6w2q1 Capstone Applying Project Management in the Real World Weekly - challenge 2

### ISSUE THREAD

**Issue by charafeddine01** [BDFD-LearningGround/Coursera_Google-Project-Management#2]
[Capstone Applying Project Management in the Real World Weekly - challenge 2.pdf](https://github.com/BDFD-LearningGround/Coursera_Google-Project-Management_OP/files/11182382/Capstone.Applying.Project.Management.in.the.Real.World.Weekly.-.challenge.2.pdf)

**Comment by bdfd** [comment]
i only upload 100% grade for futher learning reference, but thanks for you helps
